In [9]:
#Importation des librairies et chemins
import pandas as pd
import numpy as np
from pathlib import Path


#Affichage des colonnes 
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

DATA_PATH = Path("../data/consolidation-etalab-schema-irve-statique-v-2.3.1-20260625.csv")

In [10]:
#Chargement des données
df_bronze = pd.read_csv(
    DATA_PATH,
    low_memory=False
)

print("Lignes :", df_bronze.shape[0])
print("Colonnes :", df_bronze.shape[1])

Lignes : 227232
Colonnes : 52

df_bronze c'est la donnée brute qu'on ne modifie jamais

In [11]:
#Copie de dz_bronze
df = df_bronze.copy()
df.head()

,nom_amenageur,siren_amenageur,contact_amenageur,nom_operateur,contact_operateur,telephone_operateur,nom_enseigne,id_station_itinerance,id_station_local,nom_station,implantation_station,adresse_station,code_insee_commune,coordonneesXY,nbre_pdc,id_pdc_itinerance,id_pdc_local,puissance_nominale,prise_type_ef,prise_type_2,prise_type_combo_ccs,prise_type_chademo,prise_type_autre,gratuit,paiement_acte,paiement_cb,paiement_autre,tarification,condition_acces,reservation,horaires,accessibilite_pmr,restriction_gabarit,station_deux_roues,raccordement,num_pdl,date_mise_en_service,observations,date_maj,cable_t2_attache,last_modified,datagouv_dataset_id,datagouv_resource_id,datagouv_organization_or_owner,created_at,consolidated_longitude,consolidated_latitude,consolidated_code_postal,consolidated_commune,consolidated_is_lon_lat_correct,consolidated_is_code_insee_verified,consolidated_is_code_insee_modified
0,ChargePoint,NaN,info@chargepoint.com,ChargePoint,info@chargepoint.com,NaN,ACU_Poste_De_Garde_Haguenau,ATHTBE1004017,ATHTBE1004017,ACU_Poste_De_Garde_Haguenau,Parking privé à usage public,"93 route de Bitche, 67506 Haguenau Cedex",NaN,"[7.76269400,48.82561300]",4,ATHTBE1004017,ATHTBE1004017,22.0,false,true,false,false,false,false,true,true,NaN,NaN,Accès réservé,false,24/7,Accessibilité inconnue,inconnu,false,NaN,NaN,2020-07-25,EF connector is available at the site separately,2026-06-24,false,2026-06-24T21:00:21.100000+00:00,64060c2ac773dcf3fabbe5d2,b11113db-875d-41c7-8673-0cf8ad43e917,eco-movement,2023-06-28T11:46:08.539000+00:00,7.762694,48.825613,NaN,NaN,False,False,False
1,ChargePoint,NaN,info@chargepoint.com,ChargePoint,info@chargepoint.com,NaN,ACU_Poste_De_Garde_Haguenau,ATHTBE1004018,ATHTBE1004018,ACU_Poste_De_Garde_Haguenau,Parking privé à usage public,"93 route de Bitche, 67506 Haguenau Cedex",NaN,"[7.76269400,48.82561300]",4,ATHTBE1004018,ATHTBE1004018,22.0,false,true,false,false,false,false,true,true,NaN,NaN,Accès réservé,false,24/7,Accessibilité inconnue,inconnu,false,NaN,NaN,2020-07-25,EF connector is available at the site separately,2026-06-24,false,2026-06-24T21:00:21.100000+00:00,64060c2ac773dcf3fabbe5d2,b11113db-875d-41c7-8673-0cf8ad43e917,eco-movement,2023-06-28T11:46:08.539000+00:00,7.762694,48.825613,NaN,NaN,False,False,False
2,ChargePoint,NaN,info@chargepoint.com,ChargePoint,info@chargepoint.com,NaN,ACU_Poste_De_Garde_Haguenau,ATHTBE1004019,ATHTBE1004019,ACU_Poste_De_Garde_Haguenau,Parking privé à usage public,"93 route de Bitche, 67506 Haguenau Cedex",NaN,"[7.76269400,48.82561300]",4,ATHTBE1004019,ATHTBE1004019,11.0,false,true,false,false,false,false,true,true,NaN,NaN,Accès réservé,false,24/7,Accessibilité inconnue,inconnu,false,NaN,NaN,2020-07-25,EF connector is available at the site separately,2026-06-24,false,2026-06-24T21:00:21.100000+00:00,64060c2ac773dcf3fabbe5d2,b11113db-875d-41c7-8673-0cf8ad43e917,eco-movement,2023-06-28T11:46:08.539000+00:00,7.762694,48.825613,NaN,NaN,False,False,False
3,ChargePoint,NaN,info@chargepoint.com,ChargePoint,info@chargepoint.com,NaN,ACU_Poste_De_Garde_Haguenau,ATHTBE1004020,ATHTBE1004020,ACU_Poste_De_Garde_Haguenau,Parking privé à usage public,"93 route de Bitche, 67506 Haguenau Cedex",NaN,"[7.76269400,48.82561300]",4,ATHTBE1004020,ATHTBE1004020,11.0,false,true,false,false,false,false,true,true,NaN,NaN,Accès réservé,false,24/7,Accessibilité inconnue,inconnu,false,NaN,NaN,2020-07-25,EF connector is available at the site separately,2026-06-24,false,2026-06-24T21:00:21.100000+00:00,64060c2ac773dcf3fabbe5d2,b11113db-875d-41c7-8673-0cf8ad43e917,eco-movement,2023-06-28T11:46:08.539000+00:00,7.762694,48.825613,NaN,NaN,False,False,False
4,ChargePoint,NaN,info@chargepoint.com,ChargePoint,info@chargepoint.com,NaN,HAG_P22_Slave_3,ATHTBE1004957,ATHTBE1004957,HAG_P22_Slave_3,Parking privé à usage public,"Route de Bitche 93, 67500 Haguenau",NaN,"[7.76184100,48.82704000]",8,ATHTBE1004957,ATHTBE1004957,22.0,false,true,false,false,false,false,true,true,NaN,NaN,Accès réservé,true,24/7,Accessibilité inconnue,inconnu,false,NaN,NaN,2024-04-30,EF connector is available at the site separately,2026-06-24,false,2026-06-24T21:00:21.100000+00:00,64060c2ac773dcf3fabbe5d2,b11113db-875d-41c7-8673-0cf8ad43e917,eco-movement,2023-06-28T11:46:08.539000+00:00,7.761841,48.827040,NaN,NaN,False,False,False

1 - Profiling et audit qualité

In [12]:
#Vérification des colonnes
colonnes = pd.DataFrame({
    "colonne": df.columns,
    "type": df.dtypes.astype(str),
    "valeurs_non_nulles": df.notna().sum().values,
    "valeurs_nulles": df.isna().sum().values,
    "taux_nulles_%": (df.isna().mean().values * 100).round(2)
})

colonnes.sort_values("taux_nulles_%", ascending=False)

,colonne,type,valeurs_non_nulles,valeurs_nulles,taux_nulles_%
observations,observations,str,46520,180712,79.53
tarification,tarification,str,56345,170887,75.20
num_pdl,num_pdl,str,115972,111260,48.96
cable_t2_attache,cable_t2_attache,str,120491,106741,46.97
consolidated_code_postal,consolidated_code_postal,float64,134362,92870,40.87
date_mise_en_service,date_mise_en_service,str,134961,92271,40.61
siren_amenageur,siren_amenageur,float64,136247,90985,40.04
raccordement,raccordement,str,147925,79307,34.90
id_pdc_local,id_pdc_local,str,148554,78678,34.62
consolidated_commune,consolidated_commune,str,150839,76393,33.62
contact_amenageur,contact_amenageur,str,154883,72349,31.84
id_station_local,id_station_local,str,156520,70712,31.12
code_insee_commune,code_insee_commune,str,162688,64544,28.40
telephone_operateur,telephone_operateur,str,172549,54683,24.06
paiement_autre,paiement_autre,str,184957,42275,18.60
gratuit,gratuit,str,191778,35454,15.60
paiement_cb,paiement_cb,str,209805,17427,7.67
restriction_gabarit,restriction_gabarit,str,220606,6626,2.92
nom_operateur,nom_operateur,str,223247,3985,1.75
nom_amenageur,nom_amenageur,str,225915,1317,0.58
prise_type_2,prise_type_2,str,227232,0,0.00
prise_type_ef,prise_type_ef,str,227232,0,0.00
puissance_nominale,puissance_nominale,float64,227232,0,0.00
id_pdc_itinerance,id_pdc_itinerance,str,227232,0,0.00
coordonneesXY,coordonneesXY,str,227232,0,0.00
nbre_pdc,nbre_pdc,int64,227232,0,0.00
implantation_station,implantation_station,str,227232,0,0.00
adresse_station,adresse_station,str,227232,0,0.00
contact_operateur,contact_operateur,str,227232,0,0.00
nom_enseigne,nom_enseigne,str,227232,0,0.00
nom_station,nom_station,str,227232,0,0.00
id_station_itinerance,id_station_itinerance,str,227232,0,0.00
paiement_acte,paiement_acte,str,227232,0,0.00
prise_type_combo_ccs,prise_type_combo_ccs,str,227232,0,0.00
prise_type_chademo,prise_type_chademo,str,227232,0,0.00
prise_type_autre,prise_type_autre,str,227232,0,0.00
station_deux_roues,station_deux_roues,str,227232,0,0.00
reservation,reservation,str,227232,0,0.00
horaires,horaires,str,227232,0,0.00
accessibilite_pmr,accessibilite_pmr,str,227232,0,0.00
condition_acces,condition_acces,str,227232,0,0.00
datagouv_dataset_id,datagouv_dataset_id,str,227232,0,0.00
last_modified,last_modified,str,227232,0,0.00
date_maj,date_maj,str,227232,0,0.00
datagouv_organization_or_owner,datagouv_organization_or_owner,str,227232,0,0.00
datagouv_resource_id,datagouv_resource_id,str,227232,0,0.00
consolidated_longitude,consolidated_longitude,float64,227232,0,0.00
created_at,created_at,str,227232,0,0.00
consolidated_latitude,consolidated_latitude,float64,227232,0,0.00
consolidated_is_lon_lat_correct,consolidated_is_lon_lat_correct,bool,227232,0,0.00
consolidated_is_code_insee_verified,consolidated_is_code_insee_verified,bool,227232,0,0.00
consolidated_is_code_insee_modified,consolidated_is_code_insee_modified,bool,227232,0,0.00

In [13]:
#colonnes clés
colonnes_cles = [
    "id_pdc_itinerance",
    "id_station_itinerance",
    "date_maj",
    "last_modified",
    "date_mise_en_service",
    "puissance_nominale",
    "condition_acces",
    "coordonneesXY",
    "consolidated_longitude",
    "consolidated_latitude",
    "consolidated_code_postal",
    "consolidated_commune",
    "consolidated_is_lon_lat_correct"
]

df[colonnes_cles].head()

,id_pdc_itinerance,id_station_itinerance,date_maj,last_modified,date_mise_en_service,puissance_nominale,condition_acces,coordonneesXY,consolidated_longitude,consolidated_latitude,consolidated_code_postal,consolidated_commune,consolidated_is_lon_lat_correct
0,ATHTBE1004017,ATHTBE1004017,2026-06-24,2026-06-24T21:00:21.100000+00:00,2020-07-25,22.0,Accès réservé,"[7.76269400,48.82561300]",7.762694,48.825613,NaN,NaN,False
1,ATHTBE1004018,ATHTBE1004018,2026-06-24,2026-06-24T21:00:21.100000+00:00,2020-07-25,22.0,Accès réservé,"[7.76269400,48.82561300]",7.762694,48.825613,NaN,NaN,False
2,ATHTBE1004019,ATHTBE1004019,2026-06-24,2026-06-24T21:00:21.100000+00:00,2020-07-25,11.0,Accès réservé,"[7.76269400,48.82561300]",7.762694,48.825613,NaN,NaN,False
3,ATHTBE1004020,ATHTBE1004020,2026-06-24,2026-06-24T21:00:21.100000+00:00,2020-07-25,11.0,Accès réservé,"[7.76269400,48.82561300]",7.762694,48.825613,NaN,NaN,False
4,ATHTBE1004957,ATHTBE1004957,2026-06-24,2026-06-24T21:00:21.100000+00:00,2024-04-30,22.0,Accès réservé,"[7.76184100,48.82704000]",7.761841,48.827040,NaN,NaN,False

In [14]:
#Contrôle des dimensions globales
audit_global = pd.DataFrame({
    "indicateur": [
        "Nombre de lignes",
        "Nombre de colonnes",
        "Nombre de cellules",
        "Nombre total de valeurs manquantes",
        "Taux global de valeurs manquantes (%)",
        "Nombre de lignes entièrement dupliquées"
    ],
    "valeur": [
        df.shape[0],
        df.shape[1],
        df.shape[0] * df.shape[1],
        df.isna().sum().sum(),
        round(df.isna().sum().sum() / (df.shape[0] * df.shape[1]) * 100, 2),
        df.duplicated().sum()
    ]
})

audit_global

                                indicateur       valeur
0                         Nombre de lignes    227232.00
1                       Nombre de colonnes        52.00
2                       Nombre de cellules  11816064.00
3       Nombre total de valeurs manquantes   1449476.00
4    Taux global de valeurs manquantes (%)        12.27
5  Nombre de lignes entièrement dupliquées         0.00

In [18]:
# Analyse des identifiants répétés

# Nombre total de lignes du dataset
nb_lignes = len(df)

# Nombre d'identifiants de points de charge distincts
# dropna=True : les valeurs manquantes ne sont pas comptées
nb_id_pdc_uniques = df["id_pdc_itinerance"].nunique(dropna=True)

# Nombre d'identifiants manquants
nb_id_pdc_manquants = df["id_pdc_itinerance"].isna().sum()

# Nombre de lignes concernées par un identifiant répété
# keep=False marque toutes les occurrences comme doublons potentiels
nb_lignes_id_repetes = (
    df.duplicated(
        subset=["id_pdc_itinerance"],
        keep=False
    )
).sum()

# Nombre de répétitions supplémentaires
# C'est ce calcul qui correspond aux 67 094 mentionnés dans le sujet
nb_doublons = (
    df["id_pdc_itinerance"]
    .duplicated()
    .sum()
)

# Création du tableau récapitulatif
analyse_grain = pd.DataFrame({
    "indicateur": [
        "Nombre total de lignes",
        "Nombre d'id_pdc_itinerance uniques",
        "Nombre d'id_pdc_itinerance manquants",
        "Nombre de lignes avec id_pdc_itinerance répété",
        "Nombre de doublons (répétitions supplémentaires)"
    ],
    "valeur": [
        nb_lignes,
        nb_id_pdc_uniques,
        nb_id_pdc_manquants,
        nb_lignes_id_repetes,
        nb_doublons
    ]
})

analyse_grain

                                         indicateur  valeur
0                            Nombre total de lignes  227232
1                Nombre d'id_pdc_itinerance uniques  160138
2              Nombre d'id_pdc_itinerance manquants       0
3    Nombre de lignes avec id_pdc_itinerance répété  130964
4  Nombre de doublons (répétitions supplémentaires)   67094

2 - Analyse du grain et des doublons

## Analyse d'un identifiant répété

In [19]:
# Comptage du nombre d'occurrences par identifiant

repetition_id_pdc = (
    df["id_pdc_itinerance"]
    .value_counts()
    .reset_index()
)

repetition_id_pdc.columns = [
    "id_pdc_itinerance",
    "nombre_occurrences"
]

# Affichage des identifiants les plus fréquents

repetition_id_pdc.head(20)

   id_pdc_itinerance  nombre_occurrences
0       Non concerné                 118
1      FRLIBE3126085                   4
2    FRA68P680210015                   3
3    FRALLEGO0002061                   3
4    FRALLEGO0002062                   3
5    FRALLEGO0020201                   3
6    FRALLEGO0020202                   3
7    FRALLEGO0020211                   3
8    FRALLEGO0020212                   3
9    FRALLEGO0020231                   3
10   FRALLEGO0020232                   3
11   FRALLEGO0020251                   3
12   FRALLEGO0020252                   3
13   FRALLEGO0020281                   3
14   FRALLEGO0020282                   3
15   FRALLEGO0020331                   3
16   FRALLEGO0020332                   3
17   FRALLEGO0020341                   3
18   FRALLEGO0020342                   3
19   FRALLEGO0020351                   3

## Comparaison détaillée d'un identifiant répété

In [20]:
# Sélection d'un identifiant apparaissant plusieurs fois

id_test = "FRLIBE3126085"

# Affichage des lignes correspondantes

df[
    df["id_pdc_itinerance"] == id_test
][[
    "id_pdc_itinerance",
    "id_station_itinerance",
    "nom_station",
    "adresse_station",
    "puissance_nominale",
    "date_maj",
    "last_modified",
    "created_at"
]].sort_values("date_maj")

,id_pdc_itinerance,id_station_itinerance,nom_station,adresse_station,puissance_nominale,date_maj,last_modified,created_at
105427,FRLIBE3126085,FRLIBE3126085,Residence Carouge,34 Rue de lâÃÃ´Orge 91220 Brtigny-sur-Orge,22.0,2023-10-11,2026-01-09T13:01:51.509000+00:00,2026-01-09T13:01:51.318000+00:00
105428,FRLIBE3126085,FRLIBE3126085,Residence Carouge,34 Rue de l‚Äö√Ñ√¥Orge 91220 Brétigny-sur-Orge,22.0,2023-10-11,2025-11-24T21:47:43.507000+00:00,2025-11-24T21:47:43.223000+00:00
105425,FRLIBE3126085,FRLIBE3126085,Résidence Carouge,34 rue de l'Orge,7.4,2023-10-21,2024-12-06T06:47:29.008000+00:00,2023-10-21T22:11:40.997000+00:00
105426,FRLIBE3126085,FRLIBE3126085,Residence Carouge,34 Rue de l’Orge 91220 Brétigny-sur-Orge,22.0,2023-11-10,2024-12-06T06:47:51.017000+00:00,2023-11-13T09:31:03.098000+00:00

1- La puissance nominale est différente pour chaque id donc ce n'est pas des doublons(Cohérence)
2- Problème d'encodage détecté(Validité)
3- Les dates sont différentes, colonnes (created_at, last_modified) ce qui correspondent sûrement 
à plusieurs livraisons successives

## Analyses des répétitions exactes

In [21]:
# Nombre de lignes totalement identiques
nb_lignes_identiques = df.duplicated().sum()

print(
    "Nombre de lignes strictement identiques :",
    nb_lignes_identiques
)

Nombre de lignes strictement identiques : 0

### Conclusion analyse doublon

L'analyse montre qu'aucune ligne du dataset n'est strictement identique à une autre.

Les 67 094 répétitions observées concernent uniquement l'identifiant `id_pdc_itinerance`.

L'étude d'un exemple réel a montré que les lignes associées possèdent des différences de contenu (dates, puissance, libellés), ce qui suggère qu'il ne s'agit pas de doublons techniques mais potentiellement de plusieurs livraisons ou versions d'un même point de charge.

Aucune suppression ne sera effectuée à ce stade sans analyse métier complémentaire.

In [22]:
## Analyse des colonnes temporelles
df[[
    "date_maj",
    "last_modified",
    "created_at"
]].head(10)

,date_maj,last_modified,created_at
0,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
1,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
2,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
3,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
4,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
5,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
6,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
7,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
8,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00
9,2026-06-24,2026-06-24T21:00:21.100000+00:00,2023-06-28T11:46:08.539000+00:00

In [23]:
# Vérification du nombre de valeurs différentes
# dans les colonnes temporelles

df[[
    "date_maj",
    "last_modified",
    "created_at"
]].nunique()

date_maj         1220
last_modified     806
created_at        806
dtype: int64

In [24]:
##Analyse temporelle des identifiants répétés
# Exemple sur l'identifiant déjà étudié

df[
    df["id_pdc_itinerance"] == "FRLIBE3126085"
][[
    "id_pdc_itinerance",
    "date_maj",
    "last_modified",
    "created_at"
]].sort_values("date_maj")

,id_pdc_itinerance,date_maj,last_modified,created_at
105427,FRLIBE3126085,2023-10-11,2026-01-09T13:01:51.509000+00:00,2026-01-09T13:01:51.318000+00:00
105428,FRLIBE3126085,2023-10-11,2025-11-24T21:47:43.507000+00:00,2025-11-24T21:47:43.223000+00:00
105425,FRLIBE3126085,2023-10-21,2024-12-06T06:47:29.008000+00:00,2023-10-21T22:11:40.997000+00:00
105426,FRLIBE3126085,2023-11-10,2024-12-06T06:47:51.017000+00:00,2023-11-13T09:31:03.098000+00:00

In [28]:
# Conversion en datetime

df["date_maj_dt"] = pd.to_datetime(
    df["date_maj"],
    errors="coerce"
)

df["last_modified_dt"] = pd.to_datetime(
    df["last_modified"],
    errors="coerce"
)

df["created_at_dt"] = pd.to_datetime(
    df["created_at"],
    errors="coerce"
)

# Résumé statistique

resume_dates = pd.DataFrame({
    "min": [
        df["date_maj_dt"].min(),
        df["last_modified_dt"].min(),
        df["created_at_dt"].min()
    ],
    "max": [
        df["date_maj_dt"].max(),
        df["last_modified_dt"].max(),
        df["created_at_dt"].max()
    ],
    "nb_valeurs": [
        df["date_maj_dt"].count(),
        df["last_modified_dt"].count(),
        df["created_at_dt"].count()
    ]
},
index=[
    "date_maj_dt",
    "last_modified_dt",
    "created_at_dt"
])

resume_dates

,min,max,nb_valeurs
date_maj_dt,2012-09-10 00:00:00,2026-12-30 00:00:00,226940
last_modified_dt,2024-02-09 06:22:40.878000+00:00,2026-06-24 21:00:21.100000+00:00,193355
created_at_dt,2021-05-10 21:01:29.234000+00:00,2026-06-24 15:14:32.641000+00:00,227232

## Impact métier des répétitions d'identifiants

In [29]:
# Nombre total de lignes
nb_lignes = len(df)

# Nombre de bornes distinctes
nb_bornes = df["id_pdc_itinerance"].nunique()

# Nombre de répétitions supplémentaires
nb_repetitions = nb_lignes - nb_bornes

impact_grain = pd.DataFrame({
    "Indicateur": [
        "Nombre total de lignes",
        "Nombre de bornes distinctes",
        "Répétitions supplémentaires"
    ],
    "Valeur": [
        nb_lignes,
        nb_bornes,
        nb_repetitions
    ]
})

impact_grain

                    Indicateur  Valeur
0       Nombre total de lignes  227232
1  Nombre de bornes distinctes  160138
2  Répétitions supplémentaires   67094

## Journal de décisions - Grille d'audit qualité

### Problème

67 094 répétitions de l'identifiant `id_pdc_itinerance`.

### Options envisagées

- Supprimer toutes les répétitions avec `drop_duplicates()`
- Conserver uniquement la version la plus récente
- Analyser le grain avant toute suppression

### Choix retenu

Analyser le grain avant toute suppression.

### Justification métier

L'étude d'un identifiant répété a montré que les lignes ne sont pas identiques et peuvent correspondre à plusieurs versions ou livraisons d'un même point de charge.

Le sujet indique explicitement que le grain du fichier est potentiellement « point de charge × livraison ». Une suppression automatique risquerait donc de supprimer des données valides.